### ISSUE TITLE
Start development again

### ISSUE THREAD

**Issue by mmaelicke** [VForWaTer/hydrobox#4]
I have some plans to start developing into this package again.

My first plan is to check this list [raoulcollenteur/Python-Hydrology-Tools](https://github.com/raoulcollenteur/Python-Hydrology-Tools)

There are some well known and some not so well known, but awesome tools. I think some really fall into the scope of hydrobox and implementing some interfaces to these packages makes them usable with hydrobox. 

@MarcusStrobl , this would also make them usable in V-FOR-WaTer, so it might be worth it to scan the list for you as well.?
Besides that, do you have general comments concerning hydrobox (maybe especially on a WPS_toolbox interface), before I dive into work?
Also, I think we could transfer hydrobox to V-FOR-WaTer organization. That can make it more visible in the context it is developed. We could also streamline developments better in GH issues on a project board. 

I'm open to any suggestions!

**Comment by MarcusStrobl** [comment]
This list of tools looks awesome.

For the WPS_toolbox interface it would be good to get names and units of parameters. Though, as each tool has its own interface I guess these things can also be set within the interface. And I should document some standards for the wps interface.

Do you want to transfer your project completely, or should we just fork it in V-FOR-WaTer?

**Comment by mmaelicke** [comment]
I will transfer it completely.
